platform :ios, '11.0'
use_frameworks!

target 'AuthPinScreen_Example' do
  pod 'AuthPinScreen', :path => '../'

  pod 'DesignKit', :path => '../../DesignKit'
  pod 'UIUtils', :path => '../../UIUtils'
end
