platform :ios, '11.0'
use_frameworks!

target 'AuthPinScreen_Example' do
  pod 'AuthPinScreen', :path => '../'

  target 'AuthPinScreen_Tests' do
    inherit! :search_paths

    pod 'UIViewKit', :path => '../../UIViewKit'
  end
end
